events { }

http {
    server {
        listen 80;
        server_name localhost;

        # Path-based routing: Authentication service
        location /auth/ {
            rewrite ^/auth/(.*) /$1 break;
            proxy_pass http://auth:8001;
            proxy_set_header Host $host;
        }

	# Path-based routing: URL shortener service
	location /shortener/ {
       	    rewrite ^/shortener/(.*) /$1 break;
       	    proxy_pass http://url-shortener:8000;
       	    proxy_set_header Host $host;
       	}

        # Path-based routing: frontend service
        location /frontend/ {
            rewrite ^/frontend/(.*) /$1 break;
            proxy_pass http://frontend:8002;
            proxy_set_header Host $host;
        }

        # Default route
        location / {
            default_type application/json;
            return 200 '{"message":"Microservices API Gateway","services":{"auth":"/auth/","shortener":"/shortener/"},"endpoints":{"auth":{"create_user":"POST /auth/users","login":"POST /auth/users/login","verify":"POST /auth/auth/verify"},"shortener":{"create":"POST /shortener/","get":"GET /shortener/{id}","list":"GET /shortener/","update":"PUT /shortener/{id}","delete":"DELETE /shortener/{id}"}}}';
        }
    }

       server {
           listen 8000;
           server_name localhost;
    
           location / {
               proxy_pass http://url-shortener:8000;
               proxy_set_header Host $host;
           }
       }

       server {
           listen 8001;
           server_name localhost;
    
           location / {
               proxy_pass http://auth:8001;
               proxy_set_header Host $host;
           }
       }
}
